Implement cohort extraction endpoint
medizininformatik-initiative/flare pull request #179
Opened 2024-07-09 07:35 UTC by juliangruendner

2024-07-09 13:11 UTC, alexanderkiel requested changes

2024-07-09 13:13 UTC, alexanderkiel commented
Are we sure that returning a JSON array with potentially 1 million ID's is feasible?

2024-07-10 08:51 UTC, juliangruendner commented
> Are we sure that returning a JSON array with potentially 1 million ID's is feasible?

@alexanderkiel , as discussed - no -> paging will most likely be have to added in the next months:
https://github.com/medizininformatik-initiative/flare/issues/180

2024-07-10 09:14 UTC, alexanderkiel requested changes

2024-07-10 09:14 UTC, alexanderkiel commented on src/test/java/de/medizininformatikinitiative/flare/rest/QueryControllerTest.java
> +    void executeCohort() {
this is execute

2024-07-10 09:14 UTC, alexanderkiel commented on src/test/java/de/medizininformatikinitiative/flare/rest/QueryControllerTest.java
> +    void execute() throws JsonProcessingException {
this is executeCohort

2024-07-10 09:14 UTC, alexanderkiel commented on src/test/java/de/medizininformatikinitiative/flare/service/StructuredQueryServiceIT.java
> +        var result = getExecutionResult(query);
Sorry, I did see this in my last review. But we have to test the returned ID's here and not only the size.

2024-07-10 09:14 UTC, alexanderkiel commented on src/test/java/de/medizininformatikinitiative/flare/service/StructuredQueryServiceIT.java
>          assertThat(result).isOne();
Also please use StepVerifier here. The use of `block()` surely did cam from a time were I didn't know about StepVerifier.

2024-07-10 09:14 UTC, alexanderkiel commented on src/test/java/de/medizininformatikinitiative/flare/service/StructuredQueryServiceTest.java
> +                var result = getExecutionResult(query);
same as for the IT

2024-08-23 13:31 UTC, merged